b:
	/bin/bash back.sh
t:
	/bin/bash test.sh
u:
	cd lib-npm-link && /bin/bash update.sh
uf:
	cd lib-npm-link && /bin/bash update.sh force
c:
	ls -la roderic-project/react/node_modules/ | grep roderic
h:
	@echo https://github.com/stopsopa/roderic
islinked:
	@ls -la roderic-project/react/node_modules/ | grep roderic
unlink:
	/bin/bash lib-npm-link/install/unlink.sh

